// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzHaNcyFHdcMCrF7yCKksX5vB6xRTqcS4',
    appId: '1:590168074002:web:4aeab36ff82c68ea9235cb',
    messagingSenderId: '590168074002',
    projectId: 'easacc-19cd3',
    authDomain: 'easacc-19cd3.firebaseapp.com',
    storageBucket: 'easacc-19cd3.appspot.com',
    measurementId: 'G-MZBJTG5V0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjCKsQaBilca9pf3CA3P1-8ysCh-WneC8',
    appId: '1:590168074002:android:cc9ac0b50c0156e29235cb',
    messagingSenderId: '590168074002',
    projectId: 'easacc-19cd3',
    storageBucket: 'easacc-19cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SpMo2vgkZ3vV16TPLsdfeTVnlNtVSiY',
    appId: '1:590168074002:ios:ba6ef9cfd8ed9eea9235cb',
    messagingSenderId: '590168074002',
    projectId: 'easacc-19cd3',
    storageBucket: 'easacc-19cd3.appspot.com',
    iosBundleId: 'com.example.easacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-SpMo2vgkZ3vV16TPLsdfeTVnlNtVSiY',
    appId: '1:590168074002:ios:fd12a75a9fb63dd89235cb',
    messagingSenderId: '590168074002',
    projectId: 'easacc-19cd3',
    storageBucket: 'easacc-19cd3.appspot.com',
    iosBundleId: 'com.example.easacc.RunnerTests',
  );
}
